name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}; docker build . --file Dockerfile --secret id=GH_TOKEN  --tag ghcr.io/fails-components/notepadhandler:$(date +%s)
