name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg GH_TOKEN=${GITHUB_TOKEN} --tag ghcr.io/fails-components/notepadhandler:$(date +%s)
